# Generated by Django 5.0.1 on 2024-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_ID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('categoty', models.CharField(blank=True, default='High school', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_Number', models.CharField(max_length=15)),
                ('email_ID', models.EmailField(max_length=255)),
                ('college_ID', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(blank=True, max_length=100)),
                ('facebook_Link', models.URLField(blank=True, max_length=255)),
                ('linkedIn_Link', models.URLField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics')),
                ('category', models.CharField(default='general', max_length=100)),
            ],
        ),
    ]
