# Generated by Django 5.0.1 on 2024-02-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pac',
            old_name='categoty',
            new_name='category',
        ),
    ]
