# Generated by Django 5.0.1 on 2024-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_email_id_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pac',
            name='team_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
