# Generated by Django 5.0.1 on 2024-02-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pac_team_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pac',
            old_name='team_number',
            new_name='teamName',
        ),
    ]
