# Generated by Django 5.0.1 on 2024-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pac_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accomodation',
            field=models.BooleanField(default=False),
        ),
    ]
