# Generated by Django 5.0.1 on 2024-02-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('spreadsheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('rulebook', models.TextField(blank=True, null=True)),
                ('has_form', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('spreadsheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('has_form', models.BooleanField(blank=True, default=False, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('formFields', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.IntegerField(blank=True, default=1, null=True)),
                ('formFields', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('spreadsheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('rulebook', models.TextField(blank=True, null=True)),
                ('has_form', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='event.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaker')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='event.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='event.workshop')),
            ],
        ),
    ]
