# Generated by Django 5.0.1 on 2024-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
