# Generated by Django 5.0.1 on 2024-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_deadline_event_deadline_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='formFields',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='deadline',
        ),
        migrations.AddField(
            model_name='guest',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_images'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='has_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images'),
        ),
    ]
