# Generated by Django 5.0.1 on 2024-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_guest_formfields_remove_workshop_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
            ],
        ),
    ]
