# Generated by Django 5.0.1 on 2024-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clubs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='clubs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='clubs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
