# Generated by Django 5.0.1 on 2024-03-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_clubs_guest_clubs_workshop_clubs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.RemoveField(
            model_name='event',
            name='clubs',
        ),
    ]
