# Generated by Django 5.0.1 on 2024-03-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_clubs_club_remove_event_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.CharField(blank=True, choices=[(7, 'Physics and Astronomy Club'), (1, 'ACES-ACM'), (2, 'Chemical Engineering Society (CHES)'), (3, 'Mathematics Society (MathSoc)'), (4, 'Civil Engineering Forum (CEF)'), (5, 'Textile Engineering Society (TES)'), (6, 'Material Engineering Society (MES)'), (8, 'Axlr8r'), (9, 'Aeromodelling Club'), (10, 'DEVCLUB'), (11, 'Robotics Club')], max_length=100, null=True),
        ),
    ]
