# Generated by Django 5.0.1 on 2024-03-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
        migrations.AddField(
            model_name='event',
            name='clubs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
