# Generated by Django 5.0.1 on 2024-03-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_club_event_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clubs',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
