# Generated by Django 5.0.1 on 2024-03-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clubs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
