# Generated by Django 5.0.1 on 2024-02-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedBy', models.CharField(max_length=100)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('men', models.IntegerField()),
                ('women', models.IntegerField()),
                ('memberDetails', models.JSONField()),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentId', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('paymentReceived', models.BooleanField(default=False)),
                ('paymentProof', models.ImageField(
                    blank=True, null=True, upload_to='accommodation/')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
