# Generated by Django 5.0.1 on 2024-03-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='paymentProof',
        ),
    ]
