# Generated by Django 5.0.1 on 2024-02-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('details', models.JSONField()),
                ('lot', models.IntegerField(blank=True, null=True)),
                ('orderId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentReceived', models.BooleanField(default=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('paymentProof', models.ImageField(blank=True, null=True, upload_to='merchandise')),
            ],
        ),
    ]
